# Generated by Django 3.1.1 on 2021-02-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myailife_app', '0004_auto_20210224_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
    ]
