# Generated by Django 3.1.1 on 2021-03-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myailife_app', '0007_auto_20210224_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
