# Generated by Django 3.1.1 on 2021-03-08 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myailife_app', '0008_sessionobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionobject',
            name='user_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
