# Generated by Django 3.1.1 on 2021-03-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myailife_app', '0009_sessionobject_user_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionObject',
        ),
    ]
